#!/bin/bash
#
# entrypoint.sh - Initialize Kryoptic PKCS#11 tokens for cert-revocation-lab
#
# Uses Kryoptic's native PKCS#11 module (libkryoptic_pkcs11.so) with SQLite
# token storage. Built with --features pqc for ML-DSA-87 and ML-KEM-1024.
#
# Token slots are defined in kryoptic.conf (TOML). Each slot gets its own
# SQLite database. Token initialization via C_InitToken happens here; key
# generation happens later when pkispawn calls C_GenerateKeyPair().
#
# Environment variables:
#   HSM_SO_PIN    - Security Officer PIN (default: 12345678)
#   HSM_USER_PIN  - User PIN (default: 1234)

set -euo pipefail

PKCS11_MODULE="/usr/lib64/pkcs11/libkryoptic_pkcs11.so"
KRYOPTIC_CONF="/etc/kryoptic/kryoptic.conf"
TOKEN_DIR="/var/lib/kryoptic/tokens"
STATUS_FILE="/var/lib/kryoptic/status.json"

SO_PIN="${HSM_SO_PIN:-12345678}"
USER_PIN="${HSM_USER_PIN:-1234}"

# Slot labels matching kryoptic.conf [[slots]] entries
SLOT_DEFS=(
    "0:PQ Root CA"
    "1:PQ Intermediate CA"
    "2:PQ IoT Sub-CA"
    "3:PQ OCSP Responder"
    "4:PQ KRA"
    "5:RSA Ops CA"
    "6:Kipuka EST"
    "7:Akamu ACME"
    "8:PQ Agent"
)

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [kryoptic-hsm] $*"
}

log_error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [kryoptic-hsm] ERROR: $*" >&2
}

write_status() {
    local initialized="$1"
    local message="$2"
    local slot_count="$3"

    local slot_names=()
    for def in "${SLOT_DEFS[@]}"; do
        slot_names+=("${def#*:}")
    done

    cat > "${STATUS_FILE}" <<EOF
{
    "initialized": ${initialized},
    "message": "${message}",
    "slot_count": ${slot_count},
    "pkcs11_module": "${PKCS11_MODULE}",
    "token_dir": "${TOKEN_DIR}",
    "timestamp": "$(date -u '+%Y-%m-%dT%H:%M:%SZ')",
    "slots": $(jq -n '$ARGS.positional' --args "${slot_names[@]}")
}
EOF
}

main() {
    log "Starting Kryoptic HSM initialization (native PKCS#11 module)..."

    mkdir -p "${TOKEN_DIR}"

    # Copy the PKCS#11 module into the shared data volume so CA containers
    # can access it via the kryoptic-pq-data volume mount
    cp "${PKCS11_MODULE}" /var/lib/kryoptic/libkryoptic_pkcs11.so 2>/dev/null || true

    # Check if already initialized
    if [ -f "${STATUS_FILE}" ]; then
        local is_init
        is_init=$(jq -r '.initialized' "${STATUS_FILE}" 2>/dev/null || echo "false")
        if [ "${is_init}" = "true" ]; then
            log "HSM tokens already initialized. Skipping."
            exec sleep infinity
        fi
    fi

    # Verify Kryoptic PKCS#11 module
    if [ ! -f "${PKCS11_MODULE}" ]; then
        log_error "Kryoptic PKCS#11 module not found at ${PKCS11_MODULE}"
        write_status false "PKCS#11 module not found" 0
        exit 1
    fi
    log "PKCS#11 module: ${PKCS11_MODULE}"

    # Verify config exists
    if [ ! -f "${KRYOPTIC_CONF}" ]; then
        log_error "Config not found at ${KRYOPTIC_CONF}"
        write_status false "Config not found" 0
        exit 1
    fi
    log "Config: ${KRYOPTIC_CONF}"

    export KRYOPTIC_CONF

    write_status false "Initializing tokens..." 0

    # Initialize each token slot via C_InitToken
    local success_count=0
    local total=${#SLOT_DEFS[@]}

    for def in "${SLOT_DEFS[@]}"; do
        local slot_num="${def%%:*}"
        local label="${def#*:}"

        log "Initializing slot ${slot_num}: ${label}"

        if pkcs11-tool --module "${PKCS11_MODULE}" \
            --init-token --slot "${slot_num}" \
            --label "${label}" \
            --so-pin "${SO_PIN}" 2>&1; then

            # Set user PIN
            if pkcs11-tool --module "${PKCS11_MODULE}" \
                --slot "${slot_num}" \
                --login --login-type so --so-pin "${SO_PIN}" \
                --init-pin --new-pin "${USER_PIN}" 2>&1; then
                log "  Slot ${slot_num} (${label}): initialized"
                success_count=$((success_count + 1))
            else
                log_error "  Slot ${slot_num} (${label}): failed to set user PIN"
            fi
        else
            log_error "  Slot ${slot_num} (${label}): init failed"
        fi
    done

    log "Initialization complete: ${success_count}/${total} slots"

    if [ "${success_count}" -gt 0 ]; then
        write_status true "Initialized ${success_count}/${total} token slots" "${success_count}"
    else
        write_status false "No token slots initialized" 0
        log_error "HSM initialization failed"
    fi

    # List slots for verification
    log "Configured token slots:"
    pkcs11-tool --module "${PKCS11_MODULE}" --list-slots 2>&1 || true

    log "HSM ready — keys will be generated by pkispawn via C_GenerateKeyPair()"
    exec sleep infinity
}

main "$@"
