# FreeIPA Compose File - Run with: sudo podman-compose -f freeipa-compose.yml up -d
#
# FreeIPA requires systemd and must run as root (rootful podman).
# This is separate from the main podman-compose.yml which runs rootless.

version: "3.8"

services:
  freeipa:
    image: quay.io/freeipa/freeipa-server:${IPA_VERSION:-fedora-rawhide}
    container_name: freeipa
    hostname: ipa.${LAB_DOMAIN:-cert-lab.local}
    privileged: true
    environment:
      PASSWORD: ${ADMIN_PASSWORD:-RedHat123!}
      IPA_SERVER_INSTALL_OPTS: >-
        -U
        --realm=CERT-LAB.LOCAL
        --domain=cert-lab.local
        --no-ntp
        --no-host-dns
        --external-ca
        --external-ca-type=generic
    volumes:
      - freeipa-data:/data:Z
      - ./data/certs:/certs:Z
    ports:
      - "4443:443"        # HTTPS
      - "8180:80"         # HTTP
      - "3390:389"        # LDAP
      - "6360:636"        # LDAPS
      - "8800:88"         # Kerberos
      - "8800:88/udp"
      - "4640:464"        # Kpasswd
      - "4640:464/udp"
    # Let the container's native entrypoint handle installation
    # External CA mode generates CSR at /data/ipa.csr and exits
    # After signing, re-run with external-cert-file options
    healthcheck:
      test: ["CMD-SHELL", "curl -sk https://localhost/ipa/config/ca.crt || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 600s

volumes:
  freeipa-data:
