# FreeIPA Compose File - Run with: sudo podman-compose -f freeipa-compose.yml up -d
#
# FreeIPA requires systemd and must run as root (rootful podman).
# This is separate from the main podman-compose.yml which runs rootless.

version: "3.8"

services:
  freeipa:
    image: quay.io/freeipa/freeipa-server:${IPA_VERSION:-rocky-9}
    container_name: freeipa
    hostname: ipa.${LAB_DOMAIN:-cert-lab.local}
    privileged: true
    environment:
      PASSWORD: ${ADMIN_PASSWORD:-RedHat123!}
    volumes:
      - freeipa-data:/data:Z
      - ./data/certs:/certs:Z
    ports:
      - "4443:443"        # HTTPS
      - "8180:80"         # HTTP
      - "3390:389"        # LDAP
      - "6360:636"        # LDAPS
      - "8800:88"         # Kerberos
      - "8800:88/udp"
      - "4640:464"        # Kpasswd
      - "4640:464/udp"
    # First run: generates CSR at /data/ipa.csr
    # After signing CSR, run with --external-cert-file options
    command: >
      ipa-server-install -U
      --realm=CERT-LAB.LOCAL
      --domain=cert-lab.local
      --ds-password=${ADMIN_PASSWORD:-RedHat123!}
      --admin-password=${ADMIN_PASSWORD:-RedHat123!}
      --no-ntp
      --no-host-dns
      --external-ca
    healthcheck:
      test: ["CMD-SHELL", "curl -sk https://localhost/ipa/config/ca.crt || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 600s

volumes:
  freeipa-data:
