FROM registry.fedoraproject.org/fedora-minimal:latest

RUN microdnf install -y nginx openssl curl && microdnf clean all

RUN mkdir -p /var/www/crl /var/log/nginx /run/nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
