#!/bin/bash
# Demo index card for VHS tape 00
C='\033[0;36m'
B='\033[1m'
N='\033[0m'
D='\033[2m'

echo ""
echo -e "${C}╔══════════════════════════════════════════════════════════════╗${N}"
echo -e "${C}║${N}${B}   Akamu + Kipuka — Enrollment Protocol Demo Suite           ${N}${C}║${N}"
echo -e "${C}║${N}   ACME (RFC 8555) • EST (RFC 7030) • Kerberos SPNEGO       ${C}║${N}"
echo -e "${C}╚══════════════════════════════════════════════════════════════╝${N}"
echo ""
echo -e "${C}┌─────────────────────────────────────────────────────────────┐${N}"
echo -e "${C}│${N}  ${B}EST Protocol — Kipuka (RFC 7030)${N}                           ${C}│${N}"
echo -e "${C}│${N}                                                             ${C}│${N}"
echo -e "${C}│${N}    01  Server Health          kipuka-rsa.cert-lab.local      ${C}│${N}"
echo -e "${C}│${N}    02  CA Trust Chain         /cacerts (§4.1)                ${C}│${N}"
echo -e "${C}│${N}    03  CSR Attributes         /csrattrs (§4.5)              ${C}│${N}"
echo -e "${C}│${N}    04  OTP Generation         Admin API                     ${C}│${N}"
echo -e "${C}│${N}    05  OTP Inventory          Admin API                     ${C}│${N}"
echo -e "${C}│${N}    06  Device Enrollment      /simpleenroll (§4.2)          ${C}│${N}"
echo -e "${C}│${N}    07  Server-Side KeyGen     /serverkeygen (§4.4)          ${C}│${N}"
echo -e "${C}│${N}    08  Certificate Renewal    /simplereenroll (§4.3)        ${C}│${N}"
echo -e "${C}│${N}    09  Kerberos Enrollment    SPNEGO — no OTP               ${C}│${N}"
echo -e "${C}│${N}    10  Full Lifecycle         Enroll → Revoke → Confirm     ${C}│${N}"
echo -e "${C}│${N}                                                             ${C}│${N}"
echo -e "${C}├─────────────────────────────────────────────────────────────┤${N}"
echo -e "${C}│${N}  ${B}ACME Protocol — Akamu (RFC 8555)${N}                           ${C}│${N}"
echo -e "${C}│${N}                                                             ${C}│${N}"
echo -e "${C}│${N}    11  Directory Discovery    /acme/directory (§7.1.1)      ${C}│${N}"
echo -e "${C}│${N}    12  Replay Protection      Nonce handling (§7.2)         ${C}│${N}"
echo -e "${C}│${N}    13  Server Status          Health + Dogtag backend       ${C}│${N}"
echo -e "${C}│${N}    14  Certificate Profiles   Available cert types          ${C}│${N}"
echo -e "${C}│${N}    15  Kerberos EAB           SPNEGO → Account → Cert       ${C}│${N}"
echo -e "${C}│${N}    16  Renewal Information    ARI (RFC 9702)                ${C}│${N}"
echo -e "${C}│${N}    17  STAR Config            Short-Term Renewal (RFC 8739) ${C}│${N}"
echo -e "${C}│${N}                                                             ${C}│${N}"
echo -e "${C}├─────────────────────────────────────────────────────────────┤${N}"
echo -e "${C}│${N}  ${B}Cross-Protocol + Infrastructure${N}                            ${C}│${N}"
echo -e "${C}│${N}                                                             ${C}│${N}"
echo -e "${C}│${N}    18  RA Architecture        Two protocols, one CA         ${C}│${N}"
echo -e "${C}│${N}    19  Enrollment Dashboard   All ACME/EST endpoints        ${C}│${N}"
echo -e "${C}│${N}    20  Kerberos Dual          One ticket, two protocols     ${C}│${N}"
echo -e "${C}│${N}    21  Unified Revocation     Protocol-agnostic pipeline    ${C}│${N}"
echo -e "${C}│${N}                                                             ${C}│${N}"
echo -e "${C}├─────────────────────────────────────────────────────────────┤${N}"
echo -e "${C}│${N}                                                             ${C}│${N}"
echo -e "${C}│${N}  Kipuka (EST)  ─── OTP / mTLS / SPNEGO ───┐                ${C}│${N}"
echo -e "${C}│${N}  Akamu (ACME)  ─── HTTP-01 / EAB ─────────┼──▶ ${B}Dogtag${N}     ${C}│${N}"
echo -e "${C}│${N}  FreeIPA (KDC) ─── Kerberos ticket ───────▶│    ${B}IoT Sub-CA${N} ${C}│${N}"
echo -e "${C}│${N}                                                             ${C}│${N}"
echo -e "${C}└─────────────────────────────────────────────────────────────┘${N}"
echo ""
