[libdefaults]
    default_realm = CERT-LAB.LOCAL
    dns_lookup_kdc = false
    dns_lookup_realm = false
    rdns = false
    forwardable = true
    default_ccache_name = FILE:/tmp/krb5cc_%{uid}

[realms]
    CERT-LAB.LOCAL = {
        kdc = ipa.cert-lab.local:88
        admin_server = ipa.cert-lab.local:464
    }

[domain_realm]
    .cert-lab.local = CERT-LAB.LOCAL
    cert-lab.local = CERT-LAB.LOCAL
